name: CI
on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7
    - name: Run integration tests
      run: |
        for dir in spec/integration/*; do
          echo "testing $dir integration"
          BUNDLE_GEMFILE=$dir/Gemfile bundle install --jobs 4 --retry 3
          BUNDLE_GEMFILE=$dir/Gemfile bundle exec rspec $dir
        done

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - truffleruby-head
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        RUBYOPT: "--disable-error_highlight"
      run: bundle exec rake
